# Generated by Django 2.2.7 on 2019-11-16 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True)),
                ('comensales', models.IntegerField(null=True)),
                ('duracion', models.CharField(max_length=20, null=True)),
                ('tipo_comida', models.CharField(max_length=50, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='scraping_recetas_app.Categoria')),
            ],
            options={
                'db_table': 'receta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreparacionReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparacion', to='scraping_recetas_app.Receta')),
            ],
            options={
                'db_table': 'preparacion_receta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(max_length=50)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente', to='scraping_recetas_app.Receta')),
            ],
            options={
                'db_table': 'ingrediente_receta',
                'managed': True,
            },
        ),
    ]
