# Generated by Django 2.2.7 on 2019-11-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='scraping_recetas_app.Receta'),
        ),
    ]
