# Generated by Django 2.2.7 on 2019-11-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_recetas_app', '0003_auto_20191117_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nombre',
        ),
    ]
