# Generated by Django 5.0.2 on 2024-03-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_recetas_app', '0004_auto_20191117_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='scraping_recetas_app.categoria')),
            ],
            options={
                'db_table': 'subcategoria',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='scraping_recetas_app.subcategoria'),
        ),
    ]
